server:
  port: 9001

spring:
  application:
    name: user-service

  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 10.150.90.83:8848,10.150.90.83:8847,10.150.90.83:8849
      config:
        server-addr: 10.150.90.83:8848,10.150.90.83:8847,10.150.90.83:8849
        file-extension: yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&useSSL=false
    username: root
    password: vimicro

  redis:
    host: 10.150.90.236
    port: 16379
    password: myredis
    database: 7
    timeout: 10s
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: -1ms
        min-idle: 0

third-party:
  gitee:
    client-id: 7f17d6b73230bb925a1f55cda1e5daad025d5900bcbf62a0806dfb65ea389983
    client-secret: 40832da93734150b2795e3dc099b7bb20702d684f2f9d512dfc68648b55e925c
    call-back: http://localhost:9001/user/register/gitee
    token-url: https://gitee.com/oauth/token?grant_type=authorization_code&client_id=%s&client_secret=%s&redirect_uri=%s&code=%s
    user-url: https://gitee.com/api/v5/user?access_token=%s
    state: GITEE