server:
  port:

spring:
  application:
    name: sms-service

  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 10.150.90.83:8848,10.150.90.83:8847,10.150.90.83:8849
      config:
        server-addr: 10.150.90.83:8848,10.150.90.83:8847,10.150.90.83:8849
        file-extension: yaml

  redis:
    host: 10.150.90.236
    port: 16379
    password: myredis
    database: 7
    timeout: 10s
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: -1ms
        min-idle: 0
tencent:
  sms:
    secretId:
    secretKey:
    region:
    appId:
    signName:
    template-id:
      phoneCode:
      sales: